### ISSUE TITLE
Warning to not respond in helpscout ticket

### ISSUE THREAD

**Issue by maxiloc** [algolia/discourse-webhook-collector#4]
Can we do a warning as red, bold, big as possible on helpscout ticket to avoid people responding.

**Comment by Haroenv** [comment]
Is it bad to respond? I did that to save a click since responding closes by default

**Comment by maxiloc** [comment]
Are we speaking about the same thing ? When a ticket is from the discourse webhook you should not respond to it, it's just a link to the issue.

It's 2 click to close. I don't see how you can do it in less 😄, while responding.

**Comment by Haroenv** [comment]
Clicking "note" you type "answered on discourse", change the assigned person and the status; clicking reply you do the same, but assigned and status is already correct

**Comment by maxiloc** [comment]
It's better to just close it. @dzello if we can add: "you should just close it when you responded to it" that would be :fire:

**Comment by joshed-io** [comment]
Addressed by [this commit](https://github.com/algolia/discourse-webhook-collector/commit/392c202b0874982e9b656f39020e639e13fc4f36). Here's what the banner looks like:

![screenshot 2017-08-15 21 41 41](https://user-images.githubusercontent.com/174777/29347916-b27bf58a-8204-11e7-8e62-f38e5f07a3ed.png)

The banner is not at the top of the HelpScout message because it would break the message preview from the inbox home page. It's pretty loud though at the bottom and I think people will see it.
